### ISSUE TITLE
Add example workflows with all functionality of headstages we produce

### ISSUE THREAD

**Issue by ChucklesOnGitHub** [cjsha/onix-bonsai-docs#1]
Added these preliminary workflows for this in the workflows folder:
- example-hs64
- example-neuropixelsv1e
- example-neuropixelsv2e
Need: example-miniscopev4 once that one is available. RHS and NP2.0eBeta afterwards.

The point is that users that get the device have a workflow to download and a tutorial to follow to start working with it, taking into account the basic things they would want to do. Each workflow should showcase:
- headstage's main functionality (data acquisition from all devices, automatic commutation - Specific functionality such as stimulation can be reserved for each device node description.)
- data visualization
- how to write data to disk
- scripts for loading that data

This is modelled on the [existing docs Example section](https://open-ephys.github.io/onix-docs/Software%20Guide/Bonsai.ONIX/Bonsai%20Examples/index.html).
The tutorial must point users to all the necessary libraries and extensions needed to get started (or the software setup page that includes these).

Missing work:
- edit workflows to reflect how data should be saved (when to use csv vs matrixWriter, how to combine samples with the clock) and loaded. Avoid using Timestamp nodes like in the existing docs, since these would not be saving the hardware clock.
- edit hs-64 workflow to show how to use the ts4231 device (I tried [this](https://cjsha.github.io/onix-bonsai-docs/articles/device-ts4231.html) but didn't get data).
- make sure the commutator subworkflow is included appropriately (I used an Extension, but am unsure if this is preferred).
- add visualizers for neuropixels probes such as those that were [available in the old library](https://open-ephys.github.io/onix-docs/Software%20Guide/Bonsai.ONIX/Bonsai%20Examples/HeadstageNP1e.html).

**Comment by cjsha** [comment]
We're in the process of describing the kinds of tutorials we want in the version of this repo owned by open-ephys
