### ISSUE TITLE
Categorize entries into different dropdowns in "Node Guides" sidebar TOC

### ISSUE THREAD

**Issue by cjsha** [cjsha/onix-bonsai-docs#2]
In particular, put enums and classes different dropdowns. IMO, it would be ideal if we could even split classes more granularly, perhaps into the following categories:

- Nodes
  - Aggregate Nodes
  - Device Nodes
- Data frames

There does not appear to be an easy to do this in DocFx as of now.

**Comment by bparks13** [comment]
From Goncalo [here](https://github.com/neurogears/onix-refactor/issues/107#issuecomment-2231371968)

> A working convention which came out of last meeting was to adopt the <remarks> markup as a hook on which to place all frontend content for the user guide. This way DocFX processing can display only the contents of <remarks> for everything, e.g. properties, process overloads, and classes.
> 
> The rest of the doc strings can be written in C# documentation style guidelines.
> 
> All types should be listed in the TOC but grouped by "category". Roughly the following categories were mentioned:
> 
> - Headstage / Hub nodes
> - Single device nodes
> - Enums
> - Data frames / Types (other)

**Comment by cjsha** [comment]
Already fixed in [the version of this repo owned by open-ephys](https://github.com/open-ephys/onix1-bonsai-docs)
