### ISSUE TITLE
Workflow example for AnalogOutput

### ISSUE THREAD

**Issue by bparks13** [cjsha/onix-bonsai-docs#5]
A more complete workflow for the `AnalogOutput` operator needs to be developed on [this page](https://cjsha.github.io/onix-bonsai-docs/api/OpenEphys.Onix.AnalogOutput.html).

This workflow should include how to send at least one data type (i.e., array of floats) to the device.

**Comment by cjsha** [comment]
I think we settled on that an AnalogOutput workflow by itself would be ok, iirc. If so, feel free to close this issue, or else we should transfer it to the new repo. I'm trying to close out everything here for now and put all the issues in version of this repo owned by open-ephys.

**Comment by bparks13** [comment]
I agree, we can close this issue.
